### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by ProjectSky** [JabJabJab/Sledgehammer#1]
* Server version: 37.14
* Module version: 
```
ModuleManager: Starting module NPC-Spawner Version: 1.00.
ModuleManager: Starting module Basic Version: 1.02.
ModuleManager: Starting module Core Version: 1.00.
ModuleManager: Starting module Chat Version: 1.00.
ModuleManager: Starting module Territories Version: 1.00.
ModuleManager: Starting module Factions Version: 1.04_03.
```
* When i try to join the server, I got this exception.
```
Exception in thread "main" java.lang.NoClassDefFoundError: sledgehammer/wrapper/Player
        at zombie.network.GameServer.mainLoopDealWithNetData(GameServer.java:2368)
        at zombie.network.GameServer.main(GameServer.java:793)
Caused by: java.lang.ClassNotFoundException: sledgehammer.wrapper.Player
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```
* I do not know how to make it work, it seems that something is too old, thanks for any help.

**Comment by JabDoesThings** [comment]
I will be looking into conveniently packaging Craftboid with Sledgehammer, as a Jar release. I'll also look at writing ant build scripts for JAR files for plugins.

I'll keep this open until then. 

Also, Player moved to sledgehammer.objects, and was changed to a sub-class of LuaTable, so I can pass the information to Sledgehammer's Lua framework.

**Comment by ProjectSky** [comment]
> Also, Player moved to sledgehammer.objects, and was changed to a sub-class of LuaTable, so I can pass the information to Sledgehammer's Lua framework.

Ok, thanks.

**Comment by JabDoesThings** [comment]
I'm going to upload files for Sledgehammer. It's jar-ran, and will be much easier to setup.

**Comment by JabDoesThings** [comment]
https://github.com/JabJabJab/Sledgehammer/releases/tag/3.0

**Comment by ProjectSky** [comment]
> I'm going to upload files for Sledgehammer. It's jar-ran, and will be much easier to setup.

Awesome, I'll try the new version. But are you there any plans to add some documentation?

**Comment by JabDoesThings** [comment]
I do plan on adding documentation as the next phase, alongside bug-fixes for the current features of Sledgehammer, and the plug-ins made so far.

If you have any questions, you can ask me directly through Discord here: https://discord.gg/mdAubNB

**Comment by ProjectSky** [comment]
Ok, I successfully compiled the Sledgehammer jar file. I need to know how to use it, I sent a message to discord.
